#!/bin/tcsh -f


foreach x (*.tex)
echo $x
#sed -e 's/avmtmp/avm/g'   $x >$x.neu
#sed -e 's/hspaceThis/hphantom/g'   $x >$x.neu
#sed -e 's/\$\\cup\$/\\cupAVM/g'   $x >$x.neu
#sed -e 's/\\list\*(\([a-zA-Z0-9]*\))/\\listOf{\1}/g'   $x >$x.neu
#sed -e 's/\\avmset\*(\([a-zA-Z0-9]*\))/\\setOf{\1}/g'   $x >$x.neu
end


#foreach x (*.tex)
#echo $x
#sed -e 's/subind}{Scrambling/subind}{Scrambling@\{\\it Scrambling\\\/\}/g' $x >$x.neu
#perl -CIOED -p -e 's/\\isc{(\p{Script_Extensions=Han}+)}\\is{(\p{ASCII}+)}/\\isce{$1}{$2}/g' $x >$x.neu
#end

foreach x (*.tex)
printf "."
mv -f $x $x.old
mv $x.neu $x
end

printf "\n"

